// AUTO-GENERATED by scripts/seed-stripe-products.ts on 2026-02-22T17:25:14.097Z
// Do not edit manually. Re-run the seed script to regenerate.

export const STRIPE_PRICES: Record<string, { monthly: string; annual: string }> = {
  "brand_starter": {
    "monthly": "price_1T3gP4AUmNrcMJxHYxVXxjFN",
    "annual": "price_1T3gP5AUmNrcMJxH7LNzuWJa"
  },
  "brand_growth": {
    "monthly": "price_1T3gP5AUmNrcMJxH3ygiBxYE",
    "annual": "price_1T3gP5AUmNrcMJxHBdEQQYpl"
  },
  "brand_pro": {
    "monthly": "price_1T3gP6AUmNrcMJxHqgrMOIm6",
    "annual": "price_1T3gP6AUmNrcMJxHTKp7U2Xv"
  },
  "brand_scale": {
    "monthly": "price_1T3gP7AUmNrcMJxHUq9pz0Kl",
    "annual": "price_1T3gP7AUmNrcMJxHVK0uvPro"
  },
  "brand_elite": {
    "monthly": "price_1T3gP7AUmNrcMJxHDoZRQ3tX",
    "annual": "price_1T3gP8AUmNrcMJxHjDiR4Als"
  },
  "agency_base": {
    "monthly": "price_1T3gP8AUmNrcMJxH4hLud183",
    "annual": "price_1T3gP8AUmNrcMJxHPH8C3nGJ"
  },
  "agency_pro": {
    "monthly": "price_1T3gP9AUmNrcMJxHDhFLTlPX",
    "annual": "price_1T3gP9AUmNrcMJxHqWS3XZpJ"
  }
};

// Maps GMV slider index (0-4) to plan key
export const GMV_TO_PLAN: string[] = [
  'brand_starter',
  'brand_growth',
  'brand_pro',
  'brand_scale',
  'brand_elite',
];

// Maps agency tier name to plan key
export const AGENCY_TO_PLAN: Record<string, string> = {
  'Agency': 'agency_base',
  'Agency Pro': 'agency_pro',
};
