'use client';

/**
 * Message preview pane for generated creator posts: renders the Discord-dark
 * or Slack variant with a copy chip in the header. The Discord (#5865F2 /
 * #36393f) and Slack hexes appear ONLY here — these panes deliberately imitate
 * those apps' own surfaces (the documented exception to Pulse-tokens-only).
 *
 * Also home to the Discord-markdown renderer and the Discord-to-Slack text
 * converter the Create panel shares.
 */

import { Check, Clipboard } from 'lucide-react';
import { cn } from '@/lib/utils';

export function MessagePreview({
  destination, text, mentionMap, copied, onCopy,
}: {
  destination: 'discord' | 'slack';
  text: string;
  mentionMap: Record<string, string>;
  copied: boolean;
  onCopy: () => void;
}) {
  if (destination === 'discord') {
    return (
      <div className="flex flex-col overflow-hidden rounded-xl border border-border">
        <div className="flex items-center justify-between bg-[#36393f] px-4 py-2">
          <span className="text-xs font-semibold text-[#dcddde]">Discord Preview</span>
          <CopyBtn copied={copied} onClick={onCopy} variant="discord" />
        </div>
        <div className="max-h-[420px] flex-1 overflow-auto bg-[#36393f] p-4">
          <div className="whitespace-pre-wrap text-sm leading-[1.375rem] text-[#dcddde]">
            {renderDiscordMarkdown(text, mentionMap)}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col overflow-hidden rounded-xl border border-border">
      <div className="flex items-center justify-between border-b border-border bg-card px-4 py-2">
        <span className="text-xs font-semibold text-muted-foreground">Slack Preview</span>
        <CopyBtn copied={copied} onClick={onCopy} variant="neutral" />
      </div>
      <div className="max-h-[420px] flex-1 overflow-auto border-l-4 border-[var(--primary)] bg-card p-4">
        <div className="whitespace-pre-wrap text-sm leading-relaxed text-foreground">
          {text}
        </div>
      </div>
    </div>
  );
}

/** Small copy chip for preview-pane headers. `discord` keeps the blurple hex —
 *  it lives inside the Discord-imitation pane; `neutral` is Tempo chrome. */
function CopyBtn({ copied, onClick, variant }: { copied: boolean; onClick: () => void; variant: 'discord' | 'neutral' }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        'flex items-center gap-1.5 rounded-md px-3 py-1 text-xs font-semibold transition-colors',
        copied
          ? 'bg-[var(--pulse-pos)] text-white'
          : variant === 'discord'
            ? 'bg-[#5865F2] text-white hover:bg-[#4752c4]'
            : 'bg-secondary text-foreground hover:bg-muted',
      )}
    >
      {copied ? <><Check className="h-3.5 w-3.5" />Copied</> : <><Clipboard className="h-3.5 w-3.5" />Copy</>}
    </button>
  );
}

// ── Discord Markdown Renderer ───────────────────────────────────────
/** Exported for the Drops board, which renders the same Discord preview inside
 *  its own card chrome rather than the full MessagePreview pane. */
export function renderDiscordMarkdown(text: string, mentionMap: Record<string, string> = {}) {
  return text.split('\n').map((line, i) => {
    if (line.startsWith('# ')) return <div key={i} className="text-xl font-bold text-white mt-1 mb-1">{parseInline(line.slice(2), mentionMap)}</div>;
    if (line.startsWith('> ')) return <div key={i} className="border-l-[3px] border-[#4f545c] pl-3 my-0.5 text-[#b9bbbe]">{parseInline(line.slice(2), mentionMap)}</div>;
    if (line === '') return <br key={i} />;
    return <div key={i}>{parseInline(line, mentionMap)}</div>;
  });
}

/**
 * Reject anything that isn't a plain http/https URL. Stops the markdown link
 * pattern from emitting `javascript:` or `data:` URLs even though the source
 * text is generated by our own server — defence in depth in case future
 * report content ever incorporates user-supplied strings.
 */
function safeHref(raw: string): string | null {
  try {
    const url = new URL(raw);
    if (url.protocol !== 'http:' && url.protocol !== 'https:') return null;
    return url.toString();
  } catch {
    return null;
  }
}

function parseInline(text: string, mentionMap: Record<string, string> = {}): React.ReactNode {
  const parts: (string | React.ReactElement)[] = [];
  let remaining = text;
  let key = 0;

  while (remaining.length > 0) {
    const boldMatch = remaining.match(/^\*\*(.+?)\*\*/);
    if (boldMatch) { parts.push(<strong key={key++} className="font-bold text-white">{parseInline(boldMatch[1], mentionMap)}</strong>); remaining = remaining.slice(boldMatch[0].length); continue; }
    const italicMatch = remaining.match(/^\*(.+?)\*/);
    if (italicMatch) { parts.push(<em key={key++} className="italic text-[#b9bbbe]">{italicMatch[1]}</em>); remaining = remaining.slice(italicMatch[0].length); continue; }
    const linkMatch = remaining.match(/^\[(.+?)\]\((.+?)\)/);
    if (linkMatch) {
      const href = safeHref(linkMatch[2]);
      if (href) {
        parts.push(<a key={key++} href={href} target="_blank" rel="noopener noreferrer" className="text-[#00AFF4] hover:underline">{linkMatch[1]}</a>);
      } else {
        // Render as plain text so we never emit a dangerous href.
        parts.push(<span key={key++}>{linkMatch[1]}</span>);
      }
      remaining = remaining.slice(linkMatch[0].length);
      continue;
    }
    const mentionMatch = remaining.match(/^<@(\d+)>/);
    if (mentionMatch) { parts.push(<span key={key++} className="bg-[#5865F2]/20 text-[#dee0fc] rounded px-1">@{mentionMap[mentionMatch[1]] || 'user'}</span>); remaining = remaining.slice(mentionMatch[0].length); continue; }
    const nextSpecial = remaining.slice(1).search(/[\*\[<]/);
    if (nextSpecial === -1) { parts.push(remaining); break; }
    parts.push(remaining.slice(0, nextSpecial + 1));
    remaining = remaining.slice(nextSpecial + 1);
  }
  return <>{parts}</>;
}

// ── Slack Format Converter ──────────────────────────────────────────
// FALLBACK only: post types the API returns a server-built slackText for
// (daily-drop, whos-cooking) never come through here. Mentions resolve
// through the mentionMap so a creator's identity survives the conversion;
// Discord markdown links become "label (url)" — Slack renders raw
// [label](url) brackets literally.
export function toSlackFormat(discordText: string, mentionMap: Record<string, string> = {}): string {
  return discordText
    .replace(/^# (.+)$/gm, '*$1*')           // # Header -> *bold*
    .replace(/^> (.+)$/gm, '> $1')            // Keep blockquotes
    .replace(/\[([^\]]+)\]\((https?:[^)]+)\)/g, '$1 ($2)') // [label](url) -> label (url)
    .replace(/\*\*(.+?)\*\*/g, '*$1*')        // **bold** -> *bold*
    .replace(/<@(\d+)>/g, (_, id) => `@${mentionMap[id] || 'user'}`) // Mentions -> @handle
    .replace(/__(.+?)__/g, '_$1_');            // __underline__ -> _italic_
}
