import type { DispatchedParse } from '../upload/parse-dispatch';

/** Observed 202603 CREATOR schema, validated against JiYu Affiliate Center
 * July 24, 2026. This is a subset of the manual export, not a replacement. */
export const COMPASS_CREATOR_COLUMNS = [
  'Creator name', 'Creator-attributed GMV', 'Refunds', 'Est. commission',
  'Attributed orders', 'Creator-attributed items sold', 'Items refunded',
  'Videos', 'LIVE streams', 'AOV', 'Samples shipped',
] as const;

export function isCompassCreatorReport(header: Record<string, unknown> | null): boolean {
  return header !== null && Object.keys(header).length === COMPASS_CREATOR_COLUMNS.length
    && COMPASS_CREATOR_COLUMNS.every(key => Object.hasOwn(header, key));
}

/** The creator workbook has no date column: the task filename must establish
 * both ends of its reporting window before its values can enter daily facts. */
export function isCompassCreatorDay(fileName: string | null, reportDate: string): boolean {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(reportDate)) return false;
  const day = reportDate.replaceAll('-', '');
  const expected = `Transaction_Analysis_Creator_List_${day}-${day}`;
  return fileName === expected || fileName === `${expected}.xlsx`;
}

function amount(raw: unknown, integer: boolean): number {
  const text = String(raw ?? '').trim().replace(/^\$/, '');
  // Reject missing/garbled values instead of turning a mapping error into $0.
  if (!/^(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.\d{1,2})?$/.test(text)) throw new Error('invalid numeric cell');
  const value = Number(text.replaceAll(',', ''));
  if (!Number.isFinite(value) || value < 0 || (integer && !Number.isSafeInteger(value))) throw new Error('invalid numeric cell');
  return value;
}

/** Only UI-reconciled metrics enter the fact table. Counts of posts/LIVEs,
 * channel GMV, commissions and refunds remain owned by their existing source. */
export function parseCompassCreatorRows(rows: Record<string, unknown>[], brand: string, reportDate: string): DispatchedParse {
  const result: DispatchedParse = {
    table: 'creator_performance', records: [], matchedColumns: [...COMPASS_CREATOR_COLUMNS],
    missingColumns: [], totalCols: COMPASS_CREATOR_COLUMNS.length, errors: [],
    warnings: ['Partial Compass import: only affiliate GMV and items sold are updated. Existing content counts and other metrics are preserved; new rows leave those metrics unknown.'],
    totalGmv: 0, totalOrders: 0,
  };
  let cents = 0;
  const names = new Set<string>();
  rows.forEach((row, index) => {
    const name = String(row['Creator name'] ?? '').trim().toLowerCase();
    if (!name) {
      // TikTok inserts one definitions row directly below the header.
      if (index === 0 && String(row['Creator-attributed GMV'] ?? '').startsWith('GMV generated by customers who tapped on creator product links')) return;
      if (Object.values(row).every(value => value === '' || value == null)) return;
      result.errors.push(`Row ${index + 2}: missing creator name`);
      return;
    }
    try {
      if (!/^[a-z0-9_.]{1,64}$/.test(name)) throw new Error('invalid creator handle');
      if (names.has(name)) throw new Error('duplicate creator handle');
      names.add(name);
      const gmv = amount(row['Creator-attributed GMV'], false);
      const items = amount(row['Creator-attributed items sold'], true);
      const orders = amount(row['Attributed orders'], true);
      cents += Math.round(gmv * 100);
      result.totalOrders += orders;
      result.records.push({ brand, report_date: reportDate, period_type: 'daily', creator_name: name, gmv, items_sold: items });
    } catch (error) {
      result.errors.push(`Row ${index + 2}: ${error instanceof Error ? error.message : 'invalid row'}`);
    }
  });
  result.totalGmv = cents / 100;
  return result;
}
