'use client';
import { FilterSelect } from './filter-select';
import { useCallback,useEffect,useState } from 'react';
import { ArrowUpRight,Check,Copy,RefreshCw } from 'lucide-react';
import type { Campaign,CommunitySnapshot } from '@/lib/community-ops/campaign-model';
import type { OpsBrand } from '@/lib/community-ops/model';
const button='inline-flex items-center gap-2 rounded border border-border px-2.5 py-1.5 text-xs hover:bg-secondary disabled:opacity-50';
const input='w-full rounded border border-border bg-background px-2 py-1.5 text-sm';
const labels:Record<string,string>={recognition:'Creator recognition',top_videos:'Top videos',inspo:'Coaching & inspo',campaign:'Campaign momentum'};
const categoryTone:Record<string,{badge:string;edge:string}>={
 recognition:{badge:'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300',edge:'border-t-emerald-500'},
 top_videos:{badge:'bg-sky-100 text-sky-800 dark:bg-sky-950 dark:text-sky-300',edge:'border-t-sky-500'},
 inspo:{badge:'bg-violet-100 text-violet-800 dark:bg-violet-950 dark:text-violet-300',edge:'border-t-violet-500'},
 campaign:{badge:'bg-orange-100 text-orange-800 dark:bg-orange-950 dark:text-orange-300',edge:'border-t-orange-500'},
};
function CategoryLabel({category}:{category:string}){return <span className={`inline-flex rounded px-1.5 py-0.5 text-[10px] font-semibold ${categoryTone[category]?.badge??'bg-secondary text-foreground'}`}>{labels[category]??category}</span>;}

type Feed={posts:Campaign[];insights:{guild_id:string;snapshot:Partial<CommunitySnapshot>&{sharedChannels?:number};checked_at:string;error:string|null}[];channels:{channel_id:string;guild_id:string;name:string}[]};
async function read(r:Response){const d=await r.json();if(!r.ok)throw Error(d.error??'Request failed');return d;}
export type CampaignEdit={draft:string;owner:string;target:string;planned:string;version:string};
export function CommunityStudio({brand,brands,edits}:{brand:string;brands:OpsBrand[];edits:Map<string,CampaignEdit>}){
 const [feed,setFeed]=useState<Feed|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[category,setCategory]=useState('all'),[view,setView]=useState('ready'),[selected,setSelected]=useState('');
 const load=useCallback(async()=>{try{setFeed(await read(await fetch('/api/community-operations/campaigns',{cache:'no-store'})));setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),60000);return()=>clearInterval(timer);},[load]);
 async function scan(){setBusy(true);try{await read(await fetch('/api/community-operations/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guildId:brand})}));await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const posts=(feed?.posts??[]).filter(p=>(brand==='all'||p.guild_id===brand)&&(category==='all'||p.category===category)&&(view==='history'?['published','dismissed'].includes(p.status):view==='planned'?['approved','scheduled'].includes(p.status):p.status==='ready'));
 const visibleBrands=brands.filter(b=>brand==='all'||b.guild_id===brand);
 const current=posts.find(p=>p.id===selected)??posts[0];
 return <section className="space-y-2">
  <div className="flex flex-wrap items-center gap-2"><FilterSelect aria-label="Post status"  value={view} onValueChange={value=>setView(value)}><option value="ready">Ready to review</option><option value="planned">Approved & planned</option><option value="history">Post history</option></FilterSelect><FilterSelect aria-label="Post category"  value={category} onValueChange={value=>setCategory(value)}><option value="all">All post types</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</FilterSelect><span className="text-xs text-muted-foreground">{posts.length} posts</span><button className={`${button} ml-auto`} disabled={busy||brand==='all'} onClick={()=>void scan()}><RefreshCw size={13}/>{busy?'Refreshing...':'Refresh sources'}</button></div>
  {error&&<p role="alert" className="text-xs text-amber-600">{error}</p>}
  <div className="grid items-start gap-3 lg:grid-cols-[300px_minmax(0,1fr)]"><aside className="max-h-[70vh] overflow-y-auto rounded-md border border-border bg-card" aria-label="Community post list">{posts.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} aria-pressed={current?.id===p.id} className={`w-full border-b border-l-[3px] border-b-border px-3 py-3 text-left ${current?.id===p.id?'border-l-primary bg-primary/10':'border-l-transparent hover:bg-secondary/40'}`}><div className="flex justify-between gap-2 text-[11px] text-muted-foreground"><span>{brands.find(b=>b.guild_id===p.guild_id)?.name}</span><CategoryLabel category={p.category}/></div><p className="mt-1 text-sm font-medium leading-5">{p.title}</p><p className="mt-1 line-clamp-2 text-xs leading-4 text-muted-foreground">{edits.get(p.id)?.draft??p.draft}</p></button>)}{!posts.length&&<p className="p-5 text-xs text-muted-foreground">{!feed?'Loading posts...':'No posts match these filters.'}</p>}</aside><div>{current?<PostCard key={current.id} post={current} edits={edits} brand={brands.find(b=>b.guild_id===current.guild_id)?.name??''} channels={feed?.channels.filter(c=>c.guild_id===current.guild_id)??[]} onSaved={load}/>:<div className="rounded-md border border-border p-8 text-sm text-muted-foreground">{!feed?'Loading your community feed...':'Fresh suggestions appear here automatically when there is supporting evidence.'}</div>}</div></div>
  <details className="border-t border-border pt-2 text-xs text-muted-foreground"><summary className="cursor-pointer">Sources & publishing</summary><div className="mt-2 space-y-1">{visibleBrands.map(b=>{const i=feed?.insights.find(i=>i.guild_id===b.guild_id);return <p key={b.guild_id}><span className="font-medium">{b.name}</span>: creator data {i?.snapshot.creatorDate??'pending'}, videos {i?.snapshot.videoDate??'pending'}, {i?.snapshot.sharedChannels??0} shared channels.{i?.error?' '+i.error:''}</p>;})}<p>Drafts prepare automatically, at most hourly. Rankings cover reported brand accounts, including accounts outside the hired roster. Discord wins are self-reported; private tickets are excluded. Review and copy posts to Discord. Planned times do not publish automatically.</p></div></details>
 </section>;
}

function PostCard({post:p,brand,channels,onSaved,edits}:{edits:Map<string,CampaignEdit>;post:Campaign;brand:string;channels:Feed['channels'];onSaved:()=>Promise<void>}){
 const savedEdit=edits.get(p.id);
 const [draft,setDraft]=useState(savedEdit?.draft??p.draft),[owner,setOwner]=useState(savedEdit?.owner??p.owner_label),[target,setTarget]=useState(savedEdit?.target??p.target_channel??''),[planned,setPlanned]=useState(savedEdit?.planned??(p.planned_at?localDate(p.planned_at):'')),[version,setVersion]=useState(savedEdit?.version??p.updated_at),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[direction,setDirection]=useState('Make it shorter and more natural.');
 const dirty=draft!==p.draft||owner!==p.owner_label||target!==(p.target_channel??'')||planned!==(p.planned_at?localDate(p.planned_at):'');
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{if(dirty)edits.set(p.id,{draft,owner,target,planned,version});else edits.delete(p.id);},[dirty,edits,p.id,draft,owner,target,planned,version]);
 const stale=Date.parse(version)!==Date.parse(p.updated_at);
 async function save(status:Campaign['status']){setBusy(true);try{await read(await fetch('/api/community-operations/campaigns',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id,updatedAt:version,draft,status,owner,targetChannel:target||null,plannedAt:planned?new Date(planned).toISOString():null})}));edits.delete(p.id);setNotice('Saved. Nothing was sent to Discord.');await onSaved();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 async function rewrite(){setBusy(true);try{const result=await read(await fetch('/api/community-operations/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:p.id,updatedAt:version,direction})}));edits.delete(p.id);setDraft(result.draft);setVersion(result.updatedAt);setPlanned('');await onSaved();setNotice('Rewrite ready for review.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 const links=p.evidence.filter(e=>e.source==='Tempo'&&e.id.startsWith('video:')&&e.url).map(e=>e.url!);
 return <article className={`overflow-hidden rounded-md border border-border border-t-[3px] bg-card ${categoryTone[p.category]?.edge??'border-t-primary'}`}><div className="space-y-3 p-4"><div className="flex justify-between gap-3"><div className="flex items-center gap-2"><span className="text-xs font-medium text-muted-foreground">{brand}</span><CategoryLabel category={p.category}/></div><span className="rounded bg-secondary px-2 py-0.5 text-[10px] font-medium text-muted-foreground">{p.status==='ready'?'Ready to review':p.status}</span></div><h3 className="text-base font-semibold">{p.title}</h3><p className="text-sm text-muted-foreground">{p.reason}</p><label className="block text-xs font-medium">Post draft<textarea className={`${input} mt-2 min-h-28 border-primary/20 bg-primary/5 leading-5 focus:outline-none focus:ring-2 focus:ring-primary/25`} value={draft} onChange={e=>setDraft(e.target.value)}/></label>{links.map(url=><a key={url} href={url} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-xs text-primary underline">Watch source video <ArrowUpRight size={12}/></a>)}
  <details className="rounded border border-border p-2.5 text-xs"><summary className="cursor-pointer font-medium">Why this post / {p.evidence.length} sources</summary><div className="mt-3 space-y-3">{p.evidence.map(e=><div key={e.id}><p className="font-medium">{e.source} / {e.label}</p><p className="mt-1 whitespace-pre-wrap text-muted-foreground">{e.text}</p>{e.url&&<a className="mt-1 inline-block text-primary underline" href={e.url} target="_blank" rel="noreferrer">Open source</a>}</div>)}</div></details>
  <details className="text-xs"><summary className="cursor-pointer font-medium">Channel, owner & posting time</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs">Community channel<FilterSelect className="mt-1 w-full" value={target} onValueChange={value=>setTarget(value)}><option value="">Choose channel</option>{channels.map(c=><option key={c.channel_id} value={c.channel_id}>#{c.name}</option>)}</FilterSelect></label><label className="text-xs">Owner<input className={`${input} mt-1`} value={owner} onChange={e=>setOwner(e.target.value)}/></label></div><label className="block text-xs">Planned posting time (manual publishing)<input type="datetime-local" className={`${input} mt-1`} value={planned} onChange={e=>setPlanned(e.target.value)}/></label></details>
  {!['published','dismissed'].includes(p.status)&&<details className="text-xs"><summary className="cursor-pointer font-medium">Rewrite with AI</summary><label className="mt-3 block">What should change?<input className={`${input} mt-1`} value={direction} onChange={e=>setDirection(e.target.value)}/></label><button className={`${button} mt-2`} disabled={busy||stale||dirty||!direction.trim()} onClick={()=>void rewrite()}>Rewrite saved draft</button>{dirty&&<p className="mt-1 text-muted-foreground">Save your edits before asking for a rewrite.</p>}</details>}
  {stale&&<p role="alert" className="text-xs text-amber-600">Saved version changed. <button className="underline" onClick={()=>{setDraft(p.draft);setOwner(p.owner_label);setTarget(p.target_channel??'');setPlanned(p.planned_at?localDate(p.planned_at):'');setVersion(p.updated_at);}}>Load saved version</button></p>}
  <p role="status" className="text-xs text-muted-foreground">{notice}</p></div><div className="flex flex-wrap gap-2 border-t border-border bg-card p-3"><button className={`${button} border-primary bg-primary text-white hover:bg-primary/90`} disabled={busy||stale} onClick={()=>void save(planned?'scheduled':'approved')}><Check size={14}/>Save {planned?'plan':'approval'}</button><button className={button} disabled={!draft||stale} onClick={async()=>{try{await navigator.clipboard.writeText([draft,...links].join('\n\n'));setNotice('Copied with source video links. Nothing sent.');}catch{setNotice('Select the draft to copy it manually.');}}}><Copy size={14}/>Copy post</button>{target&&<a className={button} href={`https://discord.com/channels/${p.guild_id}/${target}`} target="_blank" rel="noreferrer">Open Discord <ArrowUpRight size={14}/></a>}<button className={button} disabled={busy||stale} onClick={()=>void save('published')}>I published this</button><button className={button} disabled={busy||stale} onClick={()=>void save('dismissed')}>Dismiss</button></div></article>;
}
function localDate(date:string){const d=new Date(date);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
