"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {SearchInput} from '@/components/ui/search-input';
import type {ComparisonRow,MemberState} from '@/lib/roster/discord-reconciliation';
const labels:Record<MemberState,string>={aligned:'Already aligned',missing_role:'Missing Discord role',missing_identity:'Link Discord account',identity_conflict:'Review identity conflict',not_in_server:'Not in JiYu server',unavailable:'Could not verify'};
const guidance:Record<MemberState,string>={aligned:'No change needed.',missing_role:'Would add Elites in Discord. Not applied.',missing_identity:'Link the correct account before syncing.',identity_conflict:'Resolve conflicting or duplicate account links first.',not_in_server:'Confirm membership before syncing.',unavailable:'Retry the comparison. No membership conclusion made.'};
type Result={rows:ComparisonRow[];checkedAt:string;rateLimited:boolean};
export function DiscordRoleReview(){
 const [result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 useEffect(()=>{const abort=new AbortController();fetch('/api/roster/discord-reconciliation?brand=jiyu',{signal:abort.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'Comparison failed.');if(!abort.signal.aborted)setResult(data);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Comparison failed.');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[version]);
 const rows=result?.rows??[];const visible=rows.filter(r=>(filter==='all'||(filter==='attention'?r.state!=='aligned':r.state===filter))&&r.name.toLowerCase().includes(query.toLowerCase()));
 return <main className="mx-auto max-w-6xl space-y-4 p-4 sm:p-6">
  <Link href="/roster?brand=jiyu&view=elite" className="text-xs text-muted-foreground hover:text-primary">Back to JiYu creators</Link>
  <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-medium text-primary">JIYU / ELITE CREATORS</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Discord role review</h1><p className="mt-1 text-sm text-muted-foreground">Tempo&apos;s Elite tag compared with Discord&apos;s Elites role.</p></div><Button variant="outline" size="sm" disabled={loading} onClick={()=>{setLoading(true);setError('');setVersion(v=>v+1);}}>{loading?'Checking Discord...':'Refresh comparison'}</Button></header>
  <div className="rounded-xl border border-primary/15 bg-primary/5 px-4 py-3 text-sm"><strong>Review only.</strong> No tags or roles are changed. Automatic syncing is not enabled.</div>
  <div className="grid grid-cols-3 gap-2">{[['In Tempo',rows.length],['Aligned',rows.filter(r=>r.state==='aligned').length],['Needs review',rows.filter(r=>r.state!=='aligned').length]].map(([label,value])=><div key={label} className="rounded-xl border border-border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums">{result?value:'...'}</p></div>)}</div>
  <section className="overflow-hidden rounded-xl border border-border bg-card" aria-label="Elite membership comparison"><div className="flex flex-wrap gap-2 border-b border-border p-3"><SearchInput aria-label="Find creator" placeholder="Find creator" value={query} onChange={e=>setQuery(e.target.value)} onClear={()=>setQuery('')}/><select aria-label="Comparison status" value={filter} onChange={e=>setFilter(e.target.value)} className="h-9 rounded-lg border border-border bg-background px-3 text-sm"><option value="all">All creators</option><option value="attention">Needs review</option><option value="aligned">Aligned</option><option value="missing_role">Missing role</option></select></div>
   {loading&&<p role="status" className="p-4 text-sm text-muted-foreground">Checking linked accounts and current Discord roles...{result?' Previous results remain below.':''}</p>}
   {error&&<p role="alert" className="p-4 text-sm text-red-600">{error}{result?' Results below are from the previous check.':''}</p>}
   <div className="divide-y divide-border">{visible.map(row=><div key={row.id} className="grid gap-2 px-4 py-3 sm:grid-cols-[1fr_1fr_1.4fr]"><div className="min-w-0"><p className="truncate text-sm font-medium">{row.name}</p><p className="text-xs text-muted-foreground">Tempo / Elite</p></div><span className={`self-start justify-self-start rounded-md px-2 py-1 text-xs font-medium ${row.state==='aligned'?'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300':'bg-amber-500/10 text-amber-800 dark:text-amber-300'}`}>{labels[row.state]}</span><p className="text-xs leading-5 text-muted-foreground">{guidance[row.state]}</p></div>)}</div>
   {!loading&&!error&&!visible.length&&<p className="p-4 text-sm text-muted-foreground">{rows.length?'No creators match these filters.':'No Elite tags are assigned in JiYu yet.'}</p>}
  </section>
  <footer className="space-y-2 text-xs leading-5 text-muted-foreground"><p><strong>Coverage:</strong> Only active JiYu creators tagged Elite in Tempo are checked. Discord-only Elites are not included because full member-list access is unavailable. Existing Discord memberships are preserved.</p>{result&&<p>Last checked {new Date(result.checkedAt).toLocaleString()}. {result.rateLimited?'Discord rate-limited this check; some results could not be verified.':''}</p>}</footer>
 </main>;
}
