import Stripe from 'stripe';
import * as fs from 'fs';
import * as path from 'path';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-12-18.acacia' as Stripe.LatestApiVersion,
});

interface PlanDef {
  key: string;
  name: string;
  monthlyPrice: number; // in dollars
  annualMonthlyPrice: number; // discounted monthly price for annual
  metadata: Record<string, string>;
}

const plans: PlanDef[] = [
  // Brand plans
  {
    key: 'brand_starter',
    name: 'Tempo Brand Starter',
    monthlyPrice: 499,
    annualMonthlyPrice: 399,
    metadata: { plan_type: 'brand', gmv_limit: '250000', brand_limit: '1', seat_limit: '5' },
  },
  {
    key: 'brand_growth',
    name: 'Tempo Brand Growth',
    monthlyPrice: 999,
    annualMonthlyPrice: 799,
    metadata: { plan_type: 'brand', gmv_limit: '750000', brand_limit: '1', seat_limit: '10' },
  },
  {
    key: 'brand_pro',
    name: 'Tempo Brand Pro',
    monthlyPrice: 1499,
    annualMonthlyPrice: 1199,
    metadata: { plan_type: 'brand', gmv_limit: '1500000', brand_limit: '1', seat_limit: '15' },
  },
  {
    key: 'brand_scale',
    name: 'Tempo Brand Scale',
    monthlyPrice: 1999,
    annualMonthlyPrice: 1599,
    metadata: { plan_type: 'brand', gmv_limit: '3000000', brand_limit: '1', seat_limit: '20' },
  },
  {
    key: 'brand_elite',
    name: 'Tempo Brand Elite',
    monthlyPrice: 2999,
    annualMonthlyPrice: 2399,
    metadata: { plan_type: 'brand', gmv_limit: 'unlimited', brand_limit: '1', seat_limit: 'unlimited' },
  },
  // Agency plans
  {
    key: 'agency_base',
    name: 'Tempo Agency',
    monthlyPrice: 1999,
    annualMonthlyPrice: 1599,
    metadata: { plan_type: 'agency', gmv_limit: 'unlimited', brand_limit: '3', seat_limit: '10' },
  },
  {
    key: 'agency_pro',
    name: 'Tempo Agency Pro',
    monthlyPrice: 4999,
    annualMonthlyPrice: 3999,
    metadata: { plan_type: 'agency', gmv_limit: 'unlimited', brand_limit: '15', seat_limit: 'unlimited' },
  },
];

async function seed() {
  const results: Record<string, { monthly: string; annual: string }> = {};

  for (const plan of plans) {
    console.log(`Creating product: ${plan.name}...`);

    const product = await stripe.products.create({
      name: plan.name,
      metadata: { ...plan.metadata, plan_key: plan.key },
    });

    const monthlyPrice = await stripe.prices.create({
      product: product.id,
      unit_amount: plan.monthlyPrice * 100,
      currency: 'usd',
      recurring: { interval: 'month' },
      metadata: { plan_key: plan.key, billing: 'monthly' },
    });

    const annualPrice = await stripe.prices.create({
      product: product.id,
      unit_amount: plan.annualMonthlyPrice * 12 * 100, // total annual amount
      currency: 'usd',
      recurring: { interval: 'year' },
      metadata: { plan_key: plan.key, billing: 'annual' },
    });

    results[plan.key] = {
      monthly: monthlyPrice.id,
      annual: annualPrice.id,
    };

    console.log(`  ✓ ${plan.key}: monthly=${monthlyPrice.id}, annual=${annualPrice.id}`);
  }

  // Write config file
  const configContent = `// AUTO-GENERATED by scripts/seed-stripe-products.ts on ${new Date().toISOString()}
// Do not edit manually. Re-run the seed script to regenerate.

export const STRIPE_PRICES: Record<string, { monthly: string; annual: string }> = ${JSON.stringify(results, null, 2)};

// Maps GMV slider index (0-4) to plan key
export const GMV_TO_PLAN: string[] = [
  'brand_starter',
  'brand_growth',
  'brand_pro',
  'brand_scale',
  'brand_elite',
];

// Maps agency tier name to plan key
export const AGENCY_TO_PLAN: Record<string, string> = {
  'Agency': 'agency_base',
  'Agency Pro': 'agency_pro',
};
`;

  const outPath = path.join(__dirname, '..', 'src', 'lib', 'stripe-prices.ts');
  fs.writeFileSync(outPath, configContent);
  console.log(`\n✅ Config written to ${outPath}`);
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
