import type { ReportReconciliation } from '@/lib/data/report-reconciliation';
import type { BrandClientReportData } from '@/lib/data/brand-client-report';
const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:n%1?2:0});
export function ReconciliationView({revision,report,token,brandName,periodLabel}:{revision:ReportReconciliation;report:BrandClientReportData;token:string;brandName:string;periodLabel:string}) {
return <main className="min-h-screen bg-[#faf9fc] px-4 py-10 text-[#202026] sm:px-8"><div className="mx-auto max-w-6xl">
<header className="mb-8 border-b border-[#e6e3ed] pb-7"><p className="text-xs font-bold uppercase tracking-widest text-[#7951c7]">Creators Corner / {brandName}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">August creator reconciliation</h1><p className="mt-2 text-sm text-[#66616f]">{periodLabel} / Revised {revision.revisedAt.slice(0,10)}</p><p className="mt-4 max-w-3xl text-sm leading-6">{revision.summary}</p><div className="mt-5 flex gap-3 text-sm font-semibold"><a className="rounded-lg bg-[#7951c7] px-4 py-2 text-white" href={`/api/report-pdf/${token}`}>Download PDF</a><a className="rounded-lg border border-[#ded9e8] bg-white px-4 py-2" href={`/api/report-csv/${token}`}>Download creator table</a></div></header>
<section aria-label="August sales context" className="mb-8"><h2 className="text-base font-semibold">August sales context</h2><p className="mt-1 text-xs text-[#66616f]">Brand totals retained from the original August performance report.</p><div className="mt-4 grid grid-cols-2 gap-4">{[['Total affiliate GMV',money(report.totalGmv)],['Total affiliate orders',report.totalOrders.toLocaleString('en-US')]].map(([label,value])=><div key={label} className="rounded-xl border border-[#e6e3ed] bg-white p-5"><p className="text-xs text-[#66616f]">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div></section>
<section><h2 className="text-lg font-semibold">Reviewed creator agreements &amp; invoices</h2><p className="mt-2 text-sm leading-6 text-[#66616f]">August posts are calendar-month delivery. July credits are shown separately. Invoice amounts do not indicate payment has been sent.</p><div className="mt-5 overflow-x-auto rounded-xl border border-[#e6e3ed] bg-white" tabIndex={0} role="region" aria-label="Creator reconciliation table"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#f3f0f8] text-xs text-[#62596f]"><tr>{['Creator','Agreement / window','August posts','Delivery & allocation','Invoice'].map(x=><th key={x} className="px-4 py-4 font-semibold">{x}</th>)}</tr></thead><tbody>{revision.rows.map(r=><tr key={r.handle} className="border-t border-[#eeeaf3] align-top"><td className="px-4 py-5"><p className="font-semibold">{r.name}</p><p className="mt-1 text-xs text-[#766d80]">@{r.handle}</p></td><td className="max-w-[195px] px-4 py-5 leading-6">{r.agreement}</td><td className="px-4 py-5 text-lg font-semibold tabular-nums">{r.augustPosts}</td><td className="max-w-[350px] px-4 py-5"><p className="font-medium">{r.creditedPosts}</p><p className="mt-1 text-xs leading-5 text-[#66616f]">{r.resolution}</p></td><td className="whitespace-nowrap px-4 py-5 font-semibold tabular-nums">{r.invoice===null?'Unchanged':money(r.invoice)}</td></tr>)}</tbody></table></div></section>
<footer className="mt-7 border-t border-[#e6e3ed] pt-5 text-xs leading-5 text-[#766d80]">This revision supersedes the agreement, delivery and invoice details for the creators listed above. Figures reflect the completed agency reconciliation. Other creators and sales-performance figures are outside this correction. Original report retained in Tempo.</footer></div></main>;
}
